### ISSUE TITLE
Is boost.org expired or hacked?

### ISSUE THREAD

**Issue by IbarakiKasen** [boostorg/website#682]
boost.org now shows an ad page, with valid SSL certificate. CT log shows that the certificate was issued on 2022-05-03T00:00:00Z, together with www.boost.org and lists.boost.org. Whois of boost.org says the last update is 2022-05-03T11:02:10Z.

**Comment by IbarakiKasen** [comment]
![img](https://user-images.githubusercontent.com/24918484/166463521-5579a88d-9b1e-4da8-8375-92c24cab42d6.png)

**Comment by dsommers** [comment]
Temporary workaround is to add the line below in `/etc/hosts` 

      146.20.110.251 www.boost.org

It seems somebody forgot to renew the boost.org domain in time. OpenDNS, Cloudflare DNS and Quad9 DNS serves the wrong IP address currently.  Google DNS seems to provide the right IP address.

**Comment by mjcaisse** [comment]
The renewal isn't due yet and it is on auto-renewal. There is something else going on. Trying to get to the bottom of it.

**Comment by glenfe** [comment]
It should be working now in the US. 

Some people outside the US still report problems, but that should be fixed in time. 

Michael was on the phone with the NS yesterday. The problem was on their end, because the domain was not up for renewal yet. However, though they corrected it, they still to provide us with an explanation for what happened.

We have boostcpp.org and boostlibraries.org that work reliably everywhere.

**Comment by SteveBronder** [comment]
Thank you to everyone who is working to get this resolved!
